repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        args: [--config-file, ./pyproject.toml]
        additional_dependencies: [
          pandas-stubs==2.2.2.240807,
          types-tqdm==4.66.0.20240417,
          lightgbm==4.0.0,
          xgboost==1.7.4,
        ] 

  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
