# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . -r requirements-dev.txt

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Lint with black
      run: |
        black --version
        black --check .
        
    - name: Test with pytest
      run: |
        pytest . --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
      
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: |
          junit/test-results.xml
          report.html
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      
    - name: Upload coverage pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-pytest-results
        path: coverage.xml
      if: ${{ always() }}
      
    - name: Upload coverage pytest html test results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-pytest-results
        path: htmlcov
      if: ${{ always() }}


